form_app/urls.py
from django.urls import path
from form_app import views

app_name = 'form_app'

urlpatterns = [
    path("1/", views.form1, name="form1"),
    path("2/", views.form2, name="form2"),
    path("task-list/", views.task_list, name="task_list"),
]

hello_app/urls.py
from django.urls import path
from hello_app import views

app_name = 'hello_app'

urlpatterns = [
    path("", views.hello),
    path("param/<str:name>/", views.hello_name),
    path("template/<str:name>/", views.hello_template),
    path("isitmonday/", views.is_it_monday),
    path("dtl/", views.dtl),

    path("first/", views.first_view, name="first"),
    path("second/", views.second_view, name="second"),
    path("third/<str:param>/", views.third_view, name="third"),

    path("child1/", views.child1_view, name="child1"),
    path("child2/", views.child2_view, name="child2"),
]

intro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include("hello_app.urls")),
    path("form/", include("form_app.urls")),

]

form_app/models.py
from django.db import models

# Create your models here.

orm_app/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=64)
    capital = models.OneToOneField('Capital', on_delete=models.CASCADE)


class Capital(models.Model):
    name = models.CharField(max_length=64)


class Language(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"


class Framework(models.Model):
    name = models.CharField(max_length=64)
    language = models.ForeignKey('Language', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} ({self.language})"


class Actor(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"


class Movie(models.Model):
    title = models.CharField(max_length=128)
    actors = models.ManyToManyField('Actor')

    def __str__(self):
        return f"{self.title}"

form_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

TASKS = []

def form1(request):
    data = request.GET

    task = data.get('task')
    if task:
        TASKS.append(task)

    return render(request, "form_app/form1.html")

# formularz post
def form2(request):
    if request.method == "GET":
        return render(request, "form_app/form2.html")

    elif request.method == "POST":
        data = request.POST
        task = data.get('task')

        if task:
            TASKS.append(task)
            return redirect("form_app:task_list")

        return render(request, "form_app/form2.html")
    else:
        return HttpResponse(status=405)


def task_list(request):
    return render(
        request,
        "form_app/task_list.html",
        {"tasks": TASKS}
    )

hello_app/views.py
import datetime

from django.core.mail.message import sanitize_address
from django.shortcuts import HttpResponse
from django.utils.html import escape
from django.shortcuts import render


def hello(request):
    # print(dir(request))
    return HttpResponse("hello world")


def hello_name(request, name):
    sanitize_name = escape(name)
    return HttpResponse(f"Hello, {sanitize_name}")


def hello_template(request, name):
    # return HttpResponse("hello world")
    return render(request, template_name="hello_app/hello.html", context={"name":name})


def is_it_monday(request):
    now = datetime.datetime.now()

    is_monday = now.weekday() == 0

    return render(
        request,
        template_name="hello_app/isitmonday.html",
        context={"is_monday":is_monday})


def dtl(request):
    fruits = [
        "jabłko",
        "banan",
        "winogron",
    ]
    user = {
        "name": "Jan",
        "username": "Kowalski",
        "age": 20
    }

    class Cow:
        def __init__(self, name):
            self.name = name

    cowl = Cow("Mućka")


    return render(
        request,
        template_name="hello_app/dtl.html",
        context={
            "fruits": fruits,
            "user": user,
            "cowl": cowl
        }
    )


def first_view(request):
    return render(
        request, "hello_app/first.html"
    )


def second_view(request):
    return render(
        request, "hello_app/second.html"
    )


def third_view(request, param):
    return render(
        request, "hello_app/third.html", {"param": param}
    )


def child1_view(request):
    return render(request, "hello_app/child1.html")


def child2_view(request):
    return render(request, "hello_app/child2.html")

orm_app/views.py
from django.shortcuts import render

# Create your views here.

form_app/templates/form_app/form1.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <form>
        <input type="text" name="task" placeholder="task">
        <input type="submit" value="Zapisz">
    </form>
</body>
</html>

form_app/templates/form_app/form2.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <form method="POST">{% csrf_token %}
        <input type="text" name="task" placeholder="task">
        <input type="submit" value="Zapisz">
    </form>
</body>
</html>

form_app/templates/form_app/task_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <ol>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% endfor %}
    </ol>
</body>
</html>

hello_app/templates/hello_app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>
    {% block content %}
    {%  endblock %}
</body>
</html>

hello_app/templates/hello_app/child1.html
{% extends 'hello_app/base.html' %}

{% block title %}
    Child 1
{% endblock %}

{% block content %}
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Corporis dolore ea eaque eos hic minima pariatur provident? Ad atque exercitationem magnam maiores, minus possimus praesentium repellendus, sequi sint totam voluptatem.
{% endblock %}

hello_app/templates/hello_app/child2.html
{% extends 'hello_app/base.html' %}

{% block title %}
    Child 2
{% endblock %}

{% block content %}
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate dolorem eum illum incidunt magni nihil quam, repellendus tenetur ut, velit vitae voluptas voluptatibus? Assumenda facilis in quis repellat sapiente, sit?
{% endblock %}

hello_app/templates/hello_app/dtl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2> Owoce: </h2>
    <ul>
    {% for item in fruits %}
      <li> {{ item }} </li>
    {% endfor %}
    </ul>

    <p>{{ fruits|length }}</p>
    <p>{{ fruits|join:", " }}</p>
    <p>{{ fruits|length|add:"2" }}</p>
    <p>{{ fruits|cut:"a" }}</p>
    <p>{{ fruits|upper}}</p>

    <p>{{ user.age }}</p>
    <p>{{ cowl.name }}</p>
    <p>{{ fruits.0 }}</p>

    {% for item in fruits %}
        <li> {{ forloop }}</li>
    {% endfor %}
</body>
</html>

hello_app/templates/hello_app/first.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <h2>To jest pierwsza strona</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad adipisci commodi consequatur delectus dolore eligendi itaque laudantium natus neque, nobis perspiciatis quam ratione saepe sed sequi, totam ullam vero voluptates?</p>

    Przejdź do strony <a href="{% url 'hello_app:second' %}">drugiej</a>

</body>
</html>

hello_app/templates/hello_app/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1> Hello, {{ name }} !</h1>
</body>
</html>

hello_app/templates/hello_app/isitmonday.html
<!--{% load static %}-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel = "stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>
    <h1>{% if is_monday %}
        TAK
    {% else %}
        NIE
    {% endif %}
    </h1>
</body>
</html>

hello_app/templates/hello_app/second.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <h2>To jest druga strona</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium ad aperiam assumenda, culpa dicta dolores eveniet excepturi facere ipsa magnam necessitatibus nemo non placeat quasi qui reprehenderit tempora ullam, voluptatum.</p>

    Przejdź do strony <a href="{% url 'hello_app:third' 'abc' %}">trzeciej</a>

</body>
</html>

hello_app/templates/hello_app/third.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Document</title>
</head>
<body>
    <h2>To jest trzecia strona z parametrem {{ param }}</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium ad aperiam assumenda, culpa dicta dolores eveniet excepturi facere ipsa magnam necessitatibus nemo non placeat quasi qui reprehenderit tempora ullam, voluptatum.</p>

    Przejdź do strony <a href="{% url 'hello_app:first' %}">pierwszej</a>


</body>
</html>